# Generated by Django 2.2.7 on 2019-11-06 12:48

import crud.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('short', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_datetime', models.DateField()),
                ('d_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initials', models.CharField(max_length=8, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DurationChoice',
            fields=[
                ('short', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_date', models.DateField(auto_now_add=True)),
                ('d_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Class')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceChoice',
            fields=[
                ('short', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=30, unique=True, validators=[crud.models.Student.validate_cpf])),
                ('birthdate', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=4, validators=[crud.models.Grade.validate_grade])),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_set', to='crud.Assessment')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_set', to='crud.Enrolment')),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ClassTime')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Enrolment')),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.PresenceChoice')),
            ],
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Student'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.AcademicPeriod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.DurationChoice'),
        ),
        migrations.AddField(
            model_name='class',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Discipline'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='d_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Class'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('assessment', 'enrolment'), name='assessment_enrolment'),
        ),
        migrations.AddConstraint(
            model_name='frequency',
            constraint=models.UniqueConstraint(fields=('class_time', 'enrolment'), name='unique_frequency'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('d_class', 'student'), name='unique_enrolment'),
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_discipline_name'),
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.UniqueConstraint(fields=('initials', 'course'), name='unique_discipline_initials'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('assessment_name', 'd_class'), name='assessment_class'),
        ),
    ]
