# Generated by Django 2.2.1 on 2019-09-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('short', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_datetime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initials', models.CharField(max_length=8, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('initials', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.AcademicPeriod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Course')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='DurationChoice',
            fields=[
                ('short', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PresenceChoice',
            fields=[
                ('short', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_number', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=30, unique=True)),
                ('birthdate', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.ClassTime')),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.PresenceChoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('discipline_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.DisciplineClass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.DurationChoice'),
        ),
        migrations.AddField(
            model_name='classtime',
            name='discipline_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.DisciplineClass'),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_number', models.IntegerField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Enrollment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='frequency',
            constraint=models.UniqueConstraint(fields=('class_time', 'student'), name='unique_frequency'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('discipline_class', 'student'), name='unique_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('assessment_number', 'enrollment'), name='assessment_enrollment'),
        ),
    ]
