# Generated by Django 2.2.1 on 2019-09-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_enrollment'),
        ),
    ]
