# Generated by Django 2.2.1 on 2019-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190909_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisciplineClass',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Enrolment',
        ),
        migrations.RemoveConstraint(
            model_name='assessment',
            name='assessment_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='discipline',
            name='unique_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='enrolment',
            name='unique_enrollment',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='enrollment',
            new_name='enrolment',
        ),
        migrations.RenameField(
            model_name='classtime',
            old_name='discipline_class',
            new_name='d_class',
        ),
        migrations.RenameField(
            model_name='enrolment',
            old_name='discipline_class',
            new_name='d_class',
        ),
        migrations.RenameField(
            model_name='enrolment',
            old_name='enrollment_date',
            new_name='enrolment_date',
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('assessment_number', 'enrolment'), name='assessment_enrolment'),
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_discipline'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('d_class', 'student'), name='unique_enrolment'),
        ),
    ]
