# Generated by Django 2.2.1 on 2019-09-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20190909_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
