# Generated by Django 2.2.1 on 2019-09-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_class_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discipline',
            name='unique_discipline',
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_discipline_name'),
        ),
        migrations.AddConstraint(
            model_name='discipline',
            constraint=models.UniqueConstraint(fields=('initials', 'course'), name='unique_discipline_initials'),
        ),
    ]
