# Generated by Django 2.2.1 on 2019-09-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20190910_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='assessment',
            name='assessment_enrolment',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_number',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='enrolment',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='grade',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_name',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='d_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.Class'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('assessment_name', 'd_class'), name='assessment_class'),
        ),
        migrations.AddField(
            model_name='grade',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_set', to='crud.Assessment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_set', to='crud.Enrolment'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('assessment', 'enrolment'), name='assessment_enrolment'),
        ),
    ]
