# Generated by Django 2.2.1 on 2019-09-17 11:22

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20190916_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[crud.models.Grade.validate_grade]),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=30, unique=True, validators=[crud.models.Student.validate_cpf]),
        ),
    ]
