# Generated by Django 2.2.1 on 2019-09-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20190917_0822'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='frequency',
            name='unique_frequency',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='student',
        ),
        migrations.AddField(
            model_name='frequency',
            name='enrolment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.Enrolment'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='frequency',
            constraint=models.UniqueConstraint(fields=('class_time', 'enrolment'), name='unique_frequency'),
        ),
    ]
